security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: eamillogin  

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticators:
                - App\Security\UsersAuthenticator
            entry_point: App\Security\UsersAuthenticator
        
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: app_user_home
              
            logout:
                path: app_logout
                target: app_login
            custom_authenticator: App\Security\UsersAuthenticator

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
               

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: PUBLIC_ACCESS }
