vich_uploader:
    db_driver: orm
    mappings:
        peinture_image:
            uri_prefix: /images/peintures
            upload_destination: '%kernel.project_dir%/public/uploads/peintures'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
