<?php

namespace ContainerSQujCc9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPersonne2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.mVFJjVc.App\Entity\Personne' shared service.
     *
     * @return \App\Entity\Personne
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.mVFJjVc": it needs an instance of "App\\Entity\\Personne" but this type has been excluded in "config/services.yaml".');
    }
}
