<?php

namespace ContainerXGpoIRO;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPeintureControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tpXWHkY.App\Controller\PeintureController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.tpXWHkY'] ?? $container->load('get_ServiceLocator_TpXWHkYService'));

        if (isset($container->privates['.service_locator.tpXWHkY.App\\Controller\\PeintureController::show()'])) {
            return $container->privates['.service_locator.tpXWHkY.App\\Controller\\PeintureController::show()'];
        }

        return $container->privates['.service_locator.tpXWHkY.App\\Controller\\PeintureController::show()'] = $a->withContext('App\\Controller\\PeintureController::show()', $container);
    }
}
