<?php

namespace ContainerWVIyxju;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPersonneControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mVFJjVc.App\Controller\PersonneController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mVFJjVc.App\\Controller\\PersonneController::delete()'] = ($container->privates['.service_locator.mVFJjVc'] ?? $container->load('get_ServiceLocator_MVFJjVcService'))->withContext('App\\Controller\\PersonneController::delete()', $container);
    }
}
