<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Personne extends \App\Entity\Personne implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'id' => [parent::class, 'id', null, 8],
        "\0".parent::class."\0".'cin' => [parent::class, 'cin', null, 16],
        "\0".parent::class."\0".'commentaires' => [parent::class, 'commentaires', null, 16],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null, 16],
        "\0".parent::class."\0".'prenom' => [parent::class, 'prenom', null, 16],
        "\0".parent::class."\0".'tel' => [parent::class, 'tel', null, 16],
        "\0".'App\\Entity\\User'."\0".'eamillogin' => ['App\\Entity\\User', 'eamillogin', null, 16],
        "\0".'App\\Entity\\User'."\0".'password' => ['App\\Entity\\User', 'password', null, 16],
        "\0".'App\\Entity\\User'."\0".'roles' => ['App\\Entity\\User', 'roles', null, 16],
        'cin' => [parent::class, 'cin', null, 16],
        'commentaires' => [parent::class, 'commentaires', null, 16],
        'eamillogin' => ['App\\Entity\\User', 'eamillogin', null, 16],
        'id' => [parent::class, 'id', null, 8],
        'nom' => [parent::class, 'nom', null, 16],
        'password' => ['App\\Entity\\User', 'password', null, 16],
        'prenom' => [parent::class, 'prenom', null, 16],
        'roles' => ['App\\Entity\\User', 'roles', null, 16],
        'tel' => [parent::class, 'tel', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
