<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Peinture extends \App\Entity\Peinture implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'categories' => [parent::class, 'categories', null, 16],
        "\0".parent::class."\0".'commentaires' => [parent::class, 'commentaires', null, 16],
        "\0".parent::class."\0".'date_realisation' => [parent::class, 'date_realisation', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'en_vente' => [parent::class, 'en_vente', null, 16],
        "\0".parent::class."\0".'hauteur' => [parent::class, 'hauteur', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'imageUrl' => [parent::class, 'imageUrl', null, 16],
        "\0".parent::class."\0".'largeur' => [parent::class, 'largeur', null, 16],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null, 16],
        "\0".parent::class."\0".'prix' => [parent::class, 'prix', null, 16],
        'categories' => [parent::class, 'categories', null, 16],
        'commentaires' => [parent::class, 'commentaires', null, 16],
        'date_realisation' => [parent::class, 'date_realisation', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'en_vente' => [parent::class, 'en_vente', null, 16],
        'hauteur' => [parent::class, 'hauteur', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'imageUrl' => [parent::class, 'imageUrl', null, 16],
        'largeur' => [parent::class, 'largeur', null, 16],
        'nom' => [parent::class, 'nom', null, 16],
        'prix' => [parent::class, 'prix', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
