<?php

namespace Container6GFLbNx;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPeintureControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rQewAiC.App\Controller\PeintureController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rQewAiC.App\\Controller\\PeintureController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'peinture' => ['privates', '.errored..service_locator.rQewAiC.App\\Entity\\Peinture', NULL, 'Cannot autowire service ".service_locator.rQewAiC": it needs an instance of "App\\Entity\\Peinture" but this type has been excluded in "config/services.yaml".'],
        ], [
            'peinture' => 'App\\Entity\\Peinture',
        ]))->withContext('App\\Controller\\PeintureController::show()', $container);
    }
}
