<?php

<<<<<<<< HEAD:var/cache/dev/ContainerWVIyxju/get_ServiceLocator_I9YOweHService.php
namespace ContainerWVIyxju;

========
namespace ContainerFKcbn3c;
>>>>>>>> 1a5dbf8f9b9a69f8f9fc8a66fd20c63d634debaf:var/cache/dev/ContainerFKcbn3c/get_ServiceLocator_I9YOweHService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_I9YOweHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.i9YOweH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.i9YOweH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categorie' => ['privates', '.errored..service_locator.i9YOweH.App\\Entity\\Categorie', NULL, 'Cannot autowire service ".service_locator.i9YOweH": it needs an instance of "App\\Entity\\Categorie" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'categorie' => 'App\\Entity\\Categorie',
            'entityManager' => '?',
        ]);
    }
}
