<?php

<<<<<<<< HEAD:var/cache/dev/ContainerWVIyxju/get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService.php
namespace ContainerWVIyxju;

========
namespace ContainerFKcbn3c;
>>>>>>>> 1a5dbf8f9b9a69f8f9fc8a66fd20c63d634debaf:var/cache/dev/ContainerFKcbn3c/get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zHyJIs5.kernel::registerContainerConfiguration()'] = ($container->privates['.service_locator.zHyJIs5'] ?? $container->load('get_ServiceLocator_ZHyJIs5Service'))->withContext('kernel::registerContainerConfiguration()', $container);
    }
}
