<?php

<<<<<<<< HEAD:var/cache/dev/ContainerWVIyxju/getAssetsService.php
namespace ContainerWVIyxju;

========
namespace ContainerFKcbn3c;
>>>>>>>> 1a5dbf8f9b9a69f8f9fc8a66fd20c63d634debaf:var/cache/dev/ContainerFKcbn3c/getAssetsService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAssetsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.PE.ZUUL.EasyCorp\Bundle\EasyAdminBundle\Config\Assets' shared service.
     *
     * @return \EasyCorp\Bundle\EasyAdminBundle\Config\Assets
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.PE.ZUUL": it references class "EasyCorp\\Bundle\\EasyAdminBundle\\Config\\Assets" but no such service exists.');
    }
}
