<?php

<<<<<<<< HEAD:var/cache/dev/ContainerWVIyxju/getAssetPackageService.php
namespace ContainerWVIyxju;

========
namespace ContainerFKcbn3c;
>>>>>>>> 1a5dbf8f9b9a69f8f9fc8a66fd20c63d634debaf:var/cache/dev/ContainerFKcbn3c/getAssetPackageService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAssetPackageService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'EasyCorp\Bundle\EasyAdminBundle\Asset\AssetPackage' shared service.
     *
     * @return \EasyCorp\Bundle\EasyAdminBundle\Asset\AssetPackage
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'easycorp'.\DIRECTORY_SEPARATOR.'easyadmin-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Asset'.\DIRECTORY_SEPARATOR.'AssetPackage.php';

        return $container->privates['EasyCorp\\Bundle\\EasyAdminBundle\\Asset\\AssetPackage'] = new \EasyCorp\Bundle\EasyAdminBundle\Asset\AssetPackage(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
