<?php

<<<<<<<< HEAD:var/cache/dev/ContainerWVIyxju/getCommentaireControllereditService.php
namespace ContainerWVIyxju;

========
namespace ContainerFKcbn3c;
>>>>>>>> 1a5dbf8f9b9a69f8f9fc8a66fd20c63d634debaf:var/cache/dev/ContainerFKcbn3c/getCommentaireControllereditService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentaireControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VCDmlWp.App\Controller\CommentaireController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.VCDmlWp'] ?? $container->load('get_ServiceLocator_VCDmlWpService'));

        if (isset($container->privates['.service_locator.VCDmlWp.App\\Controller\\CommentaireController::edit()'])) {
            return $container->privates['.service_locator.VCDmlWp.App\\Controller\\CommentaireController::edit()'];
        }

        return $container->privates['.service_locator.VCDmlWp.App\\Controller\\CommentaireController::edit()'] = $a->withContext('App\\Controller\\CommentaireController::edit()', $container);
    }
}
