<?php

<<<<<<<< HEAD:var/cache/dev/ContainerWVIyxju/getCategorieCrudControllercreateEditFormBuilderService.php
namespace ContainerWVIyxju;

========
namespace ContainerFKcbn3c;
>>>>>>>> 1a5dbf8f9b9a69f8f9fc8a66fd20c63d634debaf:var/cache/dev/ContainerFKcbn3c/getCategorieCrudControllercreateEditFormBuilderService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategorieCrudControllercreateEditFormBuilderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CaejQBj.App\Controller\Admin\CategorieCrudController::createEditFormBuilder()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CaejQBj.App\\Controller\\Admin\\CategorieCrudController::createEditFormBuilder()'] = ($container->privates['.service_locator.CaejQBj'] ?? $container->load('get_ServiceLocator_CaejQBjService'))->withContext('App\\Controller\\Admin\\CategorieCrudController::createEditFormBuilder()', $container);
    }
}
