<?php

<<<<<<<< HEAD:var/cache/dev/ContainerWVIyxju/getCategorieControllerindexService.php
namespace ContainerWVIyxju;

========
namespace ContainerFKcbn3c;
>>>>>>>> 1a5dbf8f9b9a69f8f9fc8a66fd20c63d634debaf:var/cache/dev/ContainerFKcbn3c/getCategorieControllerindexService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategorieControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4CyveaC.App\Controller\CategorieController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4CyveaC.App\\Controller\\CategorieController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categorieRepository' => ['privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService', true],
        ], [
            'categorieRepository' => 'App\\Repository\\CategorieRepository',
        ]))->withContext('App\\Controller\\CategorieController::index()', $container);
    }
}
