<?php

<<<<<<<< HEAD:var/cache/dev/ContainerWVIyxju/getCommentaireService.php
namespace ContainerWVIyxju;

========
namespace ContainerFKcbn3c;
>>>>>>>> 1a5dbf8f9b9a69f8f9fc8a66fd20c63d634debaf:var/cache/dev/ContainerFKcbn3c/getCommentaireService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentaireService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.EuHGgel.App\Entity\Commentaire' shared service.
     *
     * @return \App\Entity\Commentaire
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.EuHGgel": it needs an instance of "App\\Entity\\Commentaire" but this type has been excluded in "config/services.yaml".');
    }
}
