<?php

<<<<<<<< HEAD:var/cache/dev/ContainerWVIyxju/getCommentaireControllershowService.php
namespace ContainerWVIyxju;

========
namespace ContainerFKcbn3c;
>>>>>>>> 1a5dbf8f9b9a69f8f9fc8a66fd20c63d634debaf:var/cache/dev/ContainerFKcbn3c/getCommentaireControllershowService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentaireControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qI8U_m4.App\Controller\CommentaireController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qI8U_m4.App\\Controller\\CommentaireController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'commentaire' => ['privates', '.errored..service_locator.qI8U_m4.App\\Entity\\Commentaire', NULL, 'Cannot autowire service ".service_locator.qI8U_m4": it needs an instance of "App\\Entity\\Commentaire" but this type has been excluded in "config/services.yaml".'],
        ], [
            'commentaire' => 'App\\Entity\\Commentaire',
        ]))->withContext('App\\Controller\\CommentaireController::show()', $container);
    }
}
