<?php

<<<<<<<< HEAD:var/cache/dev/ContainerWVIyxju/getPeintureCrudControllerconfigureActionsService.php
namespace ContainerWVIyxju;

========
namespace ContainerFKcbn3c;
>>>>>>>> 1a5dbf8f9b9a69f8f9fc8a66fd20c63d634debaf:var/cache/dev/ContainerFKcbn3c/getPeintureCrudControllerconfigureActionsService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPeintureCrudControllerconfigureActionsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.T.Ra9lS.App\Controller\Admin\PeintureCrudController::configureActions()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.T.Ra9lS.App\\Controller\\Admin\\PeintureCrudController::configureActions()'] = ($container->privates['.service_locator.T.Ra9lS'] ?? $container->load('get_ServiceLocator_T_Ra9lSService'))->withContext('App\\Controller\\Admin\\PeintureCrudController::configureActions()', $container);
    }
}
