<?php

<<<<<<<< HEAD:var/cache/dev/ContainerWVIyxju/getPeintureControllerdeleteService.php
namespace ContainerWVIyxju;

========
namespace ContainerFKcbn3c;
>>>>>>>> 1a5dbf8f9b9a69f8f9fc8a66fd20c63d634debaf:var/cache/dev/ContainerFKcbn3c/getPeintureControllerdeleteService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPeintureControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tpXWHkY.App\Controller\PeintureController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tpXWHkY.App\\Controller\\PeintureController::delete()'] = ($container->privates['.service_locator.tpXWHkY'] ?? $container->load('get_ServiceLocator_TpXWHkYService'))->withContext('App\\Controller\\PeintureController::delete()', $container);
    }
}
