<?php

namespace ContainerFKcbn3c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPersonneControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LRbNtJl.App\Controller\PersonneController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LRbNtJl.App\\Controller\\PersonneController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'personne' => ['privates', '.errored..service_locator.LRbNtJl.App\\Entity\\Personne', NULL, 'Cannot autowire service ".service_locator.LRbNtJl": it needs an instance of "App\\Entity\\Personne" but this type has been excluded in "config/services.yaml".'],
        ], [
            'personne' => 'App\\Entity\\Personne',
        ]))->withContext('App\\Controller\\PersonneController::show()', $container);
    }
}
