<?php

<<<<<<<< HEAD:var/cache/dev/ContainerWVIyxju/getPeintureCrudControllerconfigureAssetsService.php
namespace ContainerWVIyxju;

========
namespace ContainerFKcbn3c;
>>>>>>>> 1a5dbf8f9b9a69f8f9fc8a66fd20c63d634debaf:var/cache/dev/ContainerFKcbn3c/getPeintureCrudControllerconfigureAssetsService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPeintureCrudControllerconfigureAssetsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PE.ZUUL.App\Controller\Admin\PeintureCrudController::configureAssets()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PE.ZUUL.App\\Controller\\Admin\\PeintureCrudController::configureAssets()'] = ($container->privates['.service_locator.PE.ZUUL'] ?? $container->load('get_ServiceLocator_PE_ZUULService'))->withContext('App\\Controller\\Admin\\PeintureCrudController::configureAssets()', $container);
    }
}
