<?php

<<<<<<<< HEAD:var/cache/dev/ContainerWVIyxju/getPeintureControllershowService.php
namespace ContainerWVIyxju;

========
namespace ContainerFKcbn3c;
>>>>>>>> 1a5dbf8f9b9a69f8f9fc8a66fd20c63d634debaf:var/cache/dev/ContainerFKcbn3c/getPeintureControllershowService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPeintureControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tpXWHkY.App\Controller\PeintureController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.tpXWHkY'] ?? $container->load('get_ServiceLocator_TpXWHkYService'));

        if (isset($container->privates['.service_locator.tpXWHkY.App\\Controller\\PeintureController::show()'])) {
            return $container->privates['.service_locator.tpXWHkY.App\\Controller\\PeintureController::show()'];
        }

        return $container->privates['.service_locator.tpXWHkY.App\\Controller\\PeintureController::show()'] = $a->withContext('App\\Controller\\PeintureController::show()', $container);
    }
}
