<?php

namespace Container7w2lBCm;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentaire3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.qI8U_m4.App\Entity\Commentaire' shared service.
     *
     * @return \App\Entity\Commentaire
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.qI8U_m4": it needs an instance of "App\\Entity\\Commentaire" but this type has been excluded in "config/services.yaml".');
    }
}
