<?php

namespace Container7w2lBCm;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPeintureService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.tpXWHkY.App\Entity\Peinture' shared service.
     *
     * @return \App\Entity\Peinture
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.tpXWHkY": it needs an instance of "App\\Entity\\Peinture" but this type has been excluded in "config/services.yaml".');
    }
}
