<?php

namespace Container7w2lBCm;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllernewCommentaireService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AJohlR6.App\Controller\UserController::newCommentaire()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AJohlR6.App\\Controller\\UserController::newCommentaire()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'peintureRepo' => ['privates', 'App\\Repository\\PeintureRepository', 'getPeintureRepositoryService', true],
        ], [
            'em' => '?',
            'peintureRepo' => 'App\\Repository\\PeintureRepository',
        ]))->withContext('App\\Controller\\UserController::newCommentaire()', $container);
    }
}
