<?php

namespace ContainerB0BJOSg;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MVFJjVcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mVFJjVc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mVFJjVc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'personne' => ['privates', '.errored..service_locator.mVFJjVc.App\\Entity\\Personne', NULL, 'Cannot autowire service ".service_locator.mVFJjVc": it needs an instance of "App\\Entity\\Personne" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'personne' => 'App\\Entity\\Personne',
            'entityManager' => '?',
        ]);
    }
}
