<?php

namespace ContainerB0BJOSg;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPersonneControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mVFJjVc.App\Controller\PersonneController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.mVFJjVc'] ?? $container->load('get_ServiceLocator_MVFJjVcService'));

        if (isset($container->privates['.service_locator.mVFJjVc.App\\Controller\\PersonneController::edit()'])) {
            return $container->privates['.service_locator.mVFJjVc.App\\Controller\\PersonneController::edit()'];
        }

        return $container->privates['.service_locator.mVFJjVc.App\\Controller\\PersonneController::edit()'] = $a->withContext('App\\Controller\\PersonneController::edit()', $container);
    }
}
