<?php

namespace ContainerRqJOhNw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllerdashboardService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WIZXZTO.App\Controller\UserController::dashboard()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WIZXZTO.App\\Controller\\UserController::dashboard()'] = ($container->privates['.service_locator.WIZXZTO'] ?? $container->load('get_ServiceLocator_WIZXZTOService'))->withContext('App\\Controller\\UserController::dashboard()', $container);
    }
}
