<?php

namespace ContainerT4zdivq;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPeintureControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WIZXZTO.App\Controller\PeintureController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WIZXZTO.App\\Controller\\PeintureController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'peintureRepository' => ['privates', 'App\\Repository\\PeintureRepository', 'getPeintureRepositoryService', true],
        ], [
            'peintureRepository' => 'App\\Repository\\PeintureRepository',
        ]))->withContext('App\\Controller\\PeintureController::index()', $container);
    }
}
