<?php

namespace ContainerT4zdivq;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPersonneControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BIAgEdp.App\Controller\PersonneController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BIAgEdp.App\\Controller\\PersonneController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'personneRepository' => ['privates', 'App\\Repository\\PersonneRepository', 'getPersonneRepositoryService', true],
        ], [
            'personneRepository' => 'App\\Repository\\PersonneRepository',
        ]))->withContext('App\\Controller\\PersonneController::index()', $container);
    }
}
