<?php

namespace ContainerT4zdivq;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllerdeleteCommentaireService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EuHGgel.App\Controller\UserController::deleteCommentaire()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EuHGgel.App\\Controller\\UserController::deleteCommentaire()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'commentaire' => ['privates', '.errored..service_locator.EuHGgel.App\\Entity\\Commentaire', NULL, 'Cannot autowire service ".service_locator.EuHGgel": it needs an instance of "App\\Entity\\Commentaire" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'commentaire' => 'App\\Entity\\Commentaire',
        ]))->withContext('App\\Controller\\UserController::deleteCommentaire()', $container);
    }
}
