<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX6AxJty\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX6AxJty/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX6AxJty.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX6AxJty\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerX6AxJty\App_KernelDevDebugContainer([
    'container.build_hash' => 'X6AxJty',
    'container.build_id' => '22b92579',
    'container.build_time' => 1745614674,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX6AxJty');
