<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJeetKxK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJeetKxK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJeetKxK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJeetKxK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJeetKxK\App_KernelDevDebugContainer([
    'container.build_hash' => 'JeetKxK',
    'container.build_id' => '79bbd551',
    'container.build_time' => 1746145833,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJeetKxK');
