<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRqJOhNw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRqJOhNw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRqJOhNw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRqJOhNw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRqJOhNw\App_KernelDevDebugContainer([
    'container.build_hash' => 'RqJOhNw',
    'container.build_id' => '7e8f1455',
    'container.build_time' => 1746480171,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRqJOhNw');
